router:
  default_action: "drop"
  update_interval: "5s"
  max_rules: 100

network:
  interface: "eth0"

logging:
  level: "info"
  format: "text"

# 라우팅 규칙
routing_rules:
  - id: 1
    name: "SSH 차단"
    src_ip: ""
    dst_ip: ""
    dst_port: 22
    protocol: "tcp"
    action: "drop"
    priority: 10
    enabled: true

  - id: 2
    name: "HTTP 허용"
    src_ip: ""
    dst_ip: ""
    dst_port: 80
    protocol: "tcp"
    action: "pass"
    priority: 20
    enabled: true

  - id: 3
    name: "특정 IP 차단"
    src_ip: "10.0.0.100"
    dst_ip: ""
    dst_port: 0
    protocol: ""
    action: "drop"
    priority: 5
    enabled: true
